### PR TITLE
put back docs for review purposes

### PR DESCRIPTION
**Pull request by kay-kim**
This change is [Reviewable](https://reviewable.io/reviews/kay-kim/node-mongodb-native/1)

### CODE REVIEW

**Comment by steveren** [comment]
Review status: 0 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/reference/content/index.md, line 17 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI2AGrjqSmAI8oqHMh:-KEI2AGrjqSmAI8oqHMi:1317450018) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L17)):*
The word "breaking" here makes me uneasy...how about "recent"? Unless what you mean is changes which might break your app, in which case I'd switch it to "important".

---

*[docs/reference/content/index.md, line 21 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI3RXCEg_sh0WKLm_2:-KEI3RXCEg_sh0WKLm_3:-1968067114) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L21)):*
Vague first sentence. It's a Node.js driver for MongoDB, not a MongoDB driver for Node.js. I'd change the headline to "Starting points", eliminate the sentence entirely, and go straight to the bullet-point links. I'd also add "API Documentation" to the list. 

---

*[docs/reference/content/index.md, line 28 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI5sMxwDW-fJUsZbLZ:-KEI5sMxwDW-fJUsZbL_:303585084) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L28)):*
Page formatting comment: it looks weird for the headline to be closer to the content above it than the content below it.

---

*[docs/reference/content/index.md, line 30 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI56mTDnZoWl_5dmch:-KEI56mTDnZoWl_5dmci:1683215231) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L30)):*
Some problems with this sentence. I'd rewrite it as: "If you'd like to use the MongoDB driver with ES6 features such as Promises and Generators, here are some good starting points."

---

*[docs/reference/content/index.md, line 37 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI65E1yUa4LCCN4nHF:-KEI65E1yUa4LCCN4nHG:-347464983) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L37)):*
I don't think the sentence is necessary. Skip it and go straight to the bullet links.

---

*[docs/reference/content/index.md, line 42 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI6z6Vu7PY_4uKEedD:-KEI6z6Vu7PY_4uKEedE:1727422515) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L42)):*
Seems like we could merge Next Steps and Advanced Topics into a single section.

---

*[docs/reference/content/index.md, line 50 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEI6Nx4WIt6i-NsSIBk:-KEI6Nx4WIt6i-NsSIBl:-1006722742) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/index.md#L50)):*
I don't think the FAQ link belongs under Advanced Topics. Maybe move it under Issues & Help, or give it its own top-level nav link on the left?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1)*

**Comment by steveren** [comment]
Review status: 0 of 25 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/reference/content/issues-help.md, line 11 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIQ0euQcXYWBqnuOeU:-KEIQ0evXxNLl2tNLU6H:1031420303) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L11)):*
"Lucky" seems inappropriate here. I'd say: "Our developer community is vibrant and highly engaged, with wide experience using Node.js with MongoDB."

---

*[docs/reference/content/issues-help.md, line 12 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIQj9Zu_xN-1BcfgF1:-KEIQj9_SAFXzH-IV7y4:-465184116) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L12)):*
No need for "we" here. "Often, the quickest way..."

---

*[docs/reference/content/issues-help.md, line 14 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIR31zQpmMupzpiu6j:-KEIR32-Jfngmvvrrwl1:-698493432) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L14)):*
I'd rewrite the last sentence: "Refer to our support channel documentation for more information."

---

*[docs/reference/content/issues-help.md, line 19 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIRkIHu5dWHPXvPCv1:-KEIRkIHu5dWHPXvPCv2:1064134384) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L19)):*
Better to keep this consistent with the security reporting below. "If you've found a bug..."

---

*[docs/reference/content/issues-help.md, line 34 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEISBQIdotzLxQR1vvs:-KEISBQIdotzLxQR1vvt:-57728528) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L34)):*
"guide" sounds wrong here. "review" would be better.

---

*[docs/reference/content/issues-help.md, line 36 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEISY6WlkkimKnnre80:-KEISY6WlkkimKnnre81:-2079466796) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L36)):*
Edit: "Please ensure that any pull requests pass the travis.ci checks, and include documentation and tests." Is there any way to link to an explanation of the travis.ci checks?

---

*[docs/reference/content/issues-help.md, line 47 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIT_IG-MezSrKKGvkF:-KEIT_IG-MezSrKKGvkG:-439492816) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/issues-help.md#L47)):*
Edits: "your code"

"executable in your current path"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1)*

**Comment by steveren** [comment]
Review status: 0 of 25 files reviewed at latest revision, 30 unresolved discussions.

---

*[docs/reference/content/getting-started/installation-guide.md, line 13 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIhz8rt8iyVAoKt7AM:-KEIhz8rt8iyVAoKt7AN:-1325774233) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L13)):*
Edit: "...is by using `NPM` (Node Package Manager) ." End it there.

---

*[docs/reference/content/getting-started/installation-guide.md, line 17 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIj-KZilC-coOV9LAg:-KEIj-K_T87emv6xu7Ad:-631993127) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L17)):*
I'd rewrite this as: "After you've created your project with `npm init', you can install the MongoDB driver and its dependencies with the command:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 27 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIkfXjN5n0YqFOuz0q:-KEIkfXjN5n0YqFOuz0r:-1363048866) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L27)):*
Edit: "The MongoDB driver depends on several other packages, including:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 34 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIlf8Z1ET0s8DrCWIs:-KEIlf8Z1ET0s8DrCWIt:95259658) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L34)):*
I think we need a possessive here: "...your module's dependencies."

Looking at the Node.js documentation, I don't think 'peerDependency' is meant to be used in the singular. They refer to 'peer dependencies' or to a single 'peer dependency'. See https://nodejs.org/en/blog/npm/peer-dependencies/

---

*[docs/reference/content/getting-started/installation-guide.md, line 36 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEImfmHWBuFmegSsL6G:-KEImfmIAAZD0mvg7CNP:-694121024) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L36)):*
Is this correct? NPM will attempt to download and build kerberos if you *don't* have it listed as a dependency, but NPM won't download it if you *do* have it listed? Or is the word "not" missing from the first sentence?

Also, "However" needs a comma after it.

---

*[docs/reference/content/getting-started/installation-guide.md, line 42 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIp9NCFj2GCjvxy2NM:-KEIp9NCFj2GCjvxy2NN:-1439633098) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L42)):*
Edit: "...could not resolve its peer dependency." (see above)

"However" needs a comma after it.

The next sentence I'd word like so: "You only need the `kerberos` module if you intend to use `kerberos`,  in which case you can add it to your package.json by doing the following:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 48 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIpz94XRQAa3WZ0a2h:-KEIpz94XRQAa3WZ0a2i:-1646663048) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L48)):*
I think Node.js should always have a capital N.

Last sentence should read: "Consult your UNIX operating system package manager for what libraries to install."

---

*[docs/reference/content/getting-started/installation-guide.md, line 51 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIqmvcIIpYoqa9gLUw:-KEIqmvdflkTv_ibvj9r:-782081579) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L51)):*
See above regarding "However". 

"toolchain" should be one word.

I don't think Visual Studio C++ is a thing. There's Visual Studio, and Visual C++. See https://www.visualstudio.com/en-us/features/cplusplus.aspx

---

*[docs/reference/content/getting-started/installation-guide.md, line 56 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIrod06UtJWR80FyaI:-KEIrod06UtJWR80FyaJ:616210289) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L56)):*
Node.js and Python should be capitalized.

---

*[docs/reference/content/getting-started/installation-guide.md, line 64 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIs6FgMlv4jHU1CH11:-KEIs6FgMlv4jHU1CH12:-544729140) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L64)):*
"node-gyp not found" needs formatting. End the sentence with :

---

*[docs/reference/content/getting-started/installation-guide.md, line 70 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIsO_415_deFEcWhTo:-KEIsO_415_deFEcWhTp:-1975625921) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L70)):*
Edit: "If it compiles correctly, you're ready to proceed. You can now try to install the MongoDB driver with the following command:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 77 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIsxnGfpzrUPOW6iGs:-KEIsxnGfpzrUPOW6iGt:-563299170) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L77)):*
Edit: "Re-run the command in verbose mode:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 87 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEItJprbtCnD2TvBs5J:-KEItJps_XePH6FoNHMs:-16111759) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L87)):*
Edit: "A compiler toolchain known to work for compiling `kerberos` on Windows is the following:"

---

*[docs/reference/content/getting-started/installation-guide.md, line 89 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEItfgYFyK3k-QhLtfC:-KEItfgYFyK3k-QhLtfD:713345066) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L89)):*
See above regarding Visual Studio.

---

*[docs/reference/content/getting-started/installation-guide.md, line 93 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEItm8GJ91lbwEmqxQA:-KEItm8GJ91lbwEmqxQB:770337117) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L93)):*
"Visual Studio" should be capitalized.

---

*[docs/reference/content/getting-started/installation-guide.md, line 112 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIuGGoPp1bNH0l1O_x:-KEIuGGoPp1bNH0l1O_y:1861026027) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/installation-guide.md#L112)):*
First sentence edit: "If Python is installed incorrectly, it can cause problems for `gyp`."

Node.js should be capitalized.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1)*

**Comment by steveren** [comment]
Review status: 0 of 25 files reviewed at latest revision, 54 unresolved discussions.

---

*[docs/reference/content/getting-started/quick-tour.md, line 11 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIwsL_PVajJ61Dozyh:-KEIwsL_PVajJ61Dozyi:-449200894) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L11)):*
Headline should be Quick Tour

---

*[docs/reference/content/getting-started/quick-tour.md, line 13 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIx3whkYL2PtyztH3k:-KEIx3whkYL2PtyztH3l:637524412) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L13)):*
Capitalize Node.js

Second sentence: "It covers how to set up the driver and perform simple CRUD operations."

Third sentence: "For more in-depth coverage, see the tutorials." (Link possible here?)

---

*[docs/reference/content/getting-started/quick-tour.md, line 18 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIxl1qfAD8RYkUzaiR:-KEIxl1qfAD8RYkUzaiS:1344212285) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L18)):*
First sentence unnecessary, I think. Second: "Be sure Node.js and NPM are correctly set up and included in your PATH. To install the driver:" 

---

*[docs/reference/content/getting-started/quick-tour.md, line 26 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIyWmlZ6mCimaRGvQV:-KEIyWmlZ6mCimaRGvQW:-1376051255) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L26)):*
Edit: "First, create a directory where your application will live."

---

*[docs/reference/content/getting-started/quick-tour.md, line 33 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIymEsrZAvwH_idSlj:-KEIymEsrZAvwH_idSlk:1777946874) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L33)):*
Period at the end of the sentence.

---

*[docs/reference/content/getting-started/quick-tour.md, line 39 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIyx_bdq1q31zk4XQM:-KEIyx_bdq1q31zk4XQN:-1504720305) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L39)):*
Edit: "Next, install the driver dependency."

---

*[docs/reference/content/getting-started/quick-tour.md, line 49 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIzANLlOQ4dHB0vsNd:-KEIzANLlOQ4dHB0vsNe:-1366756753) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L49)):*
Last sentence: "Next, create a database directory (in this case, under **/data**)."

---

*[docs/reference/content/getting-started/quick-tour.md, line 52 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEIzWvD2fon-WLl75va:-KEIzWvD2fon-WLl75vb:1775712427) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L52)):*
No need to specify the default port.

---

*[docs/reference/content/getting-started/quick-tour.md, line 59 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ-t7zE6QmEgQbeZSl:-KEJ-t8-uW_1ldbnvSKd:-43477377) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L59)):*
Edit: "Create a new file named **app.js**."

---

*[docs/reference/content/getting-started/quick-tour.md, line 61 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ0EghbExHSd7EDSlh:-KEJ0EghbExHSd7EDSli:1219599121) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L61)):*
Edit: "Add code to connect to the server and the database **myproject**."

---

*[docs/reference/content/getting-started/quick-tour.md, line 78 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ0d2HSoeyeAkJ-52o:-KEJ0d2HSoeyeAkJ-52p:-436258419) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L78)):*
Edit: "The application should connect successfully and print **Connected correctly to server** to the console."

---

*[docs/reference/content/getting-started/quick-tour.md, line 80 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ0i_QOdryU93BdXZ7:-KEJ0i_QOdryU93BdXZ8:1163716481) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L80)):*
Edit: "Add some code to use the different CRUD operations."

---

*[docs/reference/content/getting-started/quick-tour.md, line 84 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ12NYSaOli0WncugZ:-KEJ12NYSaOli0Wncug_:432797012) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L84)):*
Edit: "Create a function to insert some documents."

---

*[docs/reference/content/getting-started/quick-tour.md, line 103 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ27RZAyAOJNXPk0aT:-KEJ27R_hdybf6JoLEdd:34532206) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L103)):*
Edit: "The **insert** command returns an object with the following fields:"

---

*[docs/reference/content/getting-started/quick-tour.md, line 109 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ2lswCCsoNUx2ysut:-KEJ2lswCCsoNUx2ysuu:-1577226855) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L109)):*
Edit: "Next, add a call to the **insertDocuments** command to the **MongoClient.connect** method callback."

---

*[docs/reference/content/getting-started/quick-tour.md, line 128 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ39aVC_RRIDg4Yd-G:-KEJ39aVC_RRIDg4Yd-H:2082801213) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L128)):*
Edit: "Next, run the updated **app.js** file."

---

*[docs/reference/content/getting-started/quick-tour.md, line 143 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ3Xqx5PSd0d9zbPYr:-KEJ3Xqx5PSd0d9zbPYs:2046015742) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L143)):*
Edit: "Here's how to do a simple document update by adding a new field **b** to the document that has the field **a** set to **2**."

---

*[docs/reference/content/getting-started/quick-tour.md, line 160 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ4DlRrMNmx-UstlFX:-KEJ4DlSlsg1q_z9_uw7:1491128695) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L160)):*
First sentence unnecessary. Second: "Next, update the callback function from **MongoClient.connect** to include the update method."

---

*[docs/reference/content/getting-started/quick-tour.md, line 183 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ4W5LOmoXExB3Imj8:-KEJ4W5LOmoXExB3Imj9:1615274505) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L183)):*
Edit: "Next, remove the document where the field **a** is equal to **3**."

---

*[docs/reference/content/getting-started/quick-tour.md, line 199 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ4jfNZSNkIPaMjlYh:-KEJ4jfNZSNkIPaMjlYi:-1605744745) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L199)):*
First sentence unnecessary. Second: "Add the method to the **MongoClient.connect** callback function."

---

*[docs/reference/content/getting-started/quick-tour.md, line 222 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ50XC7DFxnuvLzZWn:-KEJ50XC7DFxnuvLzZWo:512920259) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L222)):*
No need for this sentence, it's in the next section.

---

*[docs/reference/content/getting-started/quick-tour.md, line 226 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ8PtG94umOD69RA8Q:-KEJ8PtG94umOD69RA8R:615672840) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L226)):*
Edit: "Finally, add a query that returns all the documents."

---

*[docs/reference/content/getting-started/quick-tour.md, line 243 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ8lU2VAlDmDKRuroP:-KEJ8lU2VAlDmDKRuroQ:-800417937) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L243)):*
Edit: "This query returns all the documents in the **documents** collection. One document was deleted earlier, so the total documents returned is **2**. Finally, add the findDocument method to the **MongoClient.connect** callback."

---

*[docs/reference/content/getting-started/quick-tour.md, line 268 \[r1\]](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1#-KEJ99xlCdN8frZAhnJa:-KEJ99xlCdN8frZAhnJb:-1554219144) ([raw file](https://github.com/kay-kim/node-mongodb-native/blob/28539040e62573b65e4d3d7fabf1fe80659b90cf/docs/reference/content/getting-started/quick-tour.md#L268)):*
Edit: "This concludes the quick tour of connecting and performing some basic CRUD operations using the MongoDB Node.js driver. For more detailed information, see the tutorials covering more specific topics of interest." (need links here)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/kay-kim/node-mongodb-native/1)*

**Comment by kay-kim** [comment]
closing since we're doing pull requests directly

**Pull request closed without merging**
